- name: "Installing git-core"
  apt: state=installed name=git-core

- name: Create system gitconfig
  copy: "dest=/etc/gitconfig content='[User]\n' force=no"

- name: "clone git project"
  git:
    repo: "{{git_repo_address}}"
    dest: "{{git_repo_dest}}"
    version: "{{git_branch_name}}"
    accept_hostkey: yes
    force: yes
  register: git_project

#- name: Fix project permission for {{git_repo_dest}} after getting git repo
#  file: state=directory dest={{git_repo_dest}} owner=ubuntu group=ubuntu recurse=true
#  when: git_repo_dest is defined
