- name: "Installing git-core"
  apt: state=installed name=git-core

- name: Create system gitconfig
  copy: "dest=/etc/gitconfig content='[User]\n' force=no"

- name: "clone git project"
  git:
    repo: "{{git_repo_address}}"
    dest: "{{git_repo_dest}}"
    version: "{{git_branch_name}}"
    accept_hostkey: yes
    force: yes
  register: git_project

